version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24  # Match EB environment platform
    commands:
      - echo Clearing npm cache...
      - npm cache clean --force
      - echo Installing Node.js dependencies...
      - npm install --no-optional
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: .
  discard-paths: no